# Funding options for WireGuard Mesh Projects
# Uncomment and configure as needed

# github: YOUR_USERNAME
# patreon: YOUR_USERNAME
# open_collective: wg-mesh-projects
# ko_fi: YOUR_USERNAME
# custom: ["https://your-donation-link.com"]
