# Funding options for WireGuard Mesh Projects
# Uncomment and configure as needed

# github: ispyisail
# patreon: ispyisail
# open_collective: wg-mesh-projects
# ko_fi: ispyisail
# custom: ["https://your-donation-link.com"]
